export const queries = [
  'batman',
  'avengers',
  'spider-man',
  'inception',
  'interstellar',
  'thor',
  'iron man',
  'black panther',
  'joker',
  'harry potter',
  'lord of the rings',
  'pirates of the caribbean',
  'the matrix',
  'deadpool',
  'guardians of the galaxy',
  'doctor strange',
  'ant man',
  'wonder woman',
  'frozen',
  'toy story',
  'finding nemo',
  'the lion king',
  'star wars',
  'mission impossible',
  'jurassic park',
  'terminator',
  'titanic',
  'avatar',
  'the dark knight',
  'shrek'
];